### ISSUE TITLE
How to enter "debug mode"?

### ISSUE THREAD

**Issue by Harti** [SteveLTN/https-portal#139]
(First of all, I _love_ this repo. It's insane how comparatively easy things get with it.)

I'm curious if there is some kind of mode to see/monitor:

* what client request enters https-portal at which port
* what https-portal thinks the request means (based on the protocol and URL found in the request)
* what containers are currently running with matching URLs
* where https-portal finally routes the request.

That is because I'm struggling to understand the basic principles that come with reverse-proxying requests. I have been confused as to how https-portal magically correctly rewrites http requests to https requests, applies the correct SSL certificate, and that working despite my app's nginx only listening on 80 and not even knowing it's going to be SSL certified. 

/edit:
Tapping into the portal using `docker-compose exec https-portal bash`, `cd /etc/nginx/conf.d` I now see the automatically generated nginx configs, how they apply the certs and how they 301 from http to ssl. But that still doesn't completely explain how I can't put e.g. `www.example.com => example.com` (it won't work), among other issues I would later open issues for if I can't resolve them myself.

**Comment by SteveLTN** [comment]
I didn't put a debug mode because I think this is a fairly simple Nginx setup. I think tapping into the docker container is the easiest way to see what's going on. You can manually change the configuration of Nginx so it prints the debug log. 

But my suggestion is if you don't understand how reverse proxy works, try to set up your own Nginx as a reverse-proxy to practice. It's not that hard at all. 

You can't put `www.example.com => example.com` is because `=>` means redirection, not proxying. `->` is for proxying. And also, you need the protocol name. So if you want to set `example.com` as the upstream for `www.example.com`, you need to use `www.example.com -> http://example.com`.

**Comment by Harti** [comment]
Thank you! The biggest issue I have with the protocols is that I always want it to be https, but sometimes when I reference my upstream using https://, it will cause a “too many redirects” error. Some of my Laravel/OctoberCMS installations require me to add some rewrite rules to my nginx config (in the respective app container), causing things to sometimes break for no apparent reason.

My latest issue is that when people try visiting my websites using Edge browser, the proxy won’t force SSL, and therefore the browser says my website is malicious, lol.

Is there some general rule of thumb of what you should do when your app container is running nginx on port 80/http only? Is the SSL certificate https-portal generates for the respective domain sufficient? Do I ever have to expose 443/https on my app container for things to work better?

**Comment by SteveLTN** [comment]
First of all, you should not reference your upstream using https. If your upstream supports https, you don't need HTTPS-PORTAL at all. 

The proxy forces SSL by performing a redirection. There might be something else wrong about your certs (maybe it's in staging mode?)

Same as the first question. Your app container should expose 80 only, because usually they are not capable of handling https requests on 443. In the rare case when they can, you don't need HTTPS-PORTAL at all, expose 443 of your app to public and it's done.

**Comment by Harti** [comment]
Thanks again for your swift and detailed reply! I think I now understand it a lot better. 


> In the rare case when they can, you don't need HTTPS-PORTAL at all, expose 443 of your app to public and it's done.

You're right, I wouldn't _need_ it, but certainly would _want_ it in that case also. It is _the_ entrypoint for my server and proxies/routes any request to the corresponding app depending on the subdomain. It's cleaner this way (using https-portal), because installing nginx on my server just to route to such exception apps would cause unnecessary additional bloat.
