### ISSUE TITLE
SIGHUP should reload Nginx

### ISSUE THREAD

**Issue by prilka** [SteveLTN/https-portal#187]
With the original Nginx-Image it's possible to reload Nginx with a SIGHUP signal: 
`docker kill -s HUP <container>`

Nginx will reload the config and refresh a few things (such as dns-resolving for backends etc.) without any downtime. The container does not stop/restart.

Sending SIGHUP to Https-Portal stops the container (same as SIGTERM).

**Comment by SteveLTN** [comment]
Hi, I did a brief research about it. It's the process management tool `s6-overlay` who doesn't forward HUP to the underlying processes. Unfortunately we have to use `s6-overlay` because Nginx isn't the only process we need to run in the container. 

I haven't found a way to make `s6-overlay` to forward the signals to Nginx. If you found it please let me know. Thanks!

**Comment by prilka** [comment]
Unfortunately, I have no experience with `s6-overlay`. Therefore I am not able to help with this issue :disappointed:

But it would be a nice feature. I often use `SIGHUP` with the original image in continuous deployment environments where Nginx sometimes does not find it's backends after container recreation.

**Comment by SteveLTN** [comment]
I'm closing this issue since we can't really do anything about it.
