### ISSUE TITLE
Use predefined static certificates

### ISSUE THREAD

**Issue by regnete** [SteveLTN/https-portal#196]
Thanks for providing this nice peace of software.

Not all domains served by our host should be secured via Let's Encrypt. Some domains must use static certifkates from other providers.
Is it possible to provide a static cert for a domain? If yes, what are the naming conventions?

**Comment by SteveLTN** [comment]
Though I don't know why you need to use another certificate since LE's are free, but in case you need:

check out [this code snippet](https://github.com/SteveLTN/https-portal/blob/master/fs_overlay/opt/certs_manager/lib/open_ssl.rb#L24-L26) and [this code snippet](https://github.com/SteveLTN/https-portal/blob/master/fs_overlay/opt/certs_manager/models/domain.rb#L17-L19). You need to provide the signed certs at `/var/lib/https-portal/#{name}/#{stage}/signed.crt` then HTTPS-PORTAL would just use it. 

Of course you can also customize Nginx configuration and not put these domains in the environment variables.

**Comment by regnete** [comment]
Wow. Thanks for the quick reply.

I guess the key file follows the same naming convention and should be placed at `/var/lib/https-portal/#{name}/#{stage}/signed.key` ?

For us it is a common scenario, that some of our customers don't want to use let's encrypt but provide us with static certificates.

**Comment by SteveLTN** [comment]
Hi,

Check [this file](https://github.com/SteveLTN/https-portal/blob/master/fs_overlay/opt/certs_manager/models/domain.rb).  All file paths are defined in their corresponding methods. For example the key is named `domain.key` in  the same path as `signed.crt`.

**Comment by regnete** [comment]
thx.
