### ISSUE TITLE
Does not support TLS 1.3

### ISSUE THREAD

**Issue by MarcelWaldvogel** [SteveLTN/https-portal#301]
I recently ran [Qualys SSLTest](https://www.ssllabs.com/ssltest/) across one of my domains and was surprised to find that TLS 1.3 was not recognized. (Confirmed by [tls.imirhil.fr](https://tls.imirhil.fr/) and Firefox; did not find out how to see the TLS version in Chrome).

From [this SO answer](https://stackoverflow.com/a/61535286), I tried the following:
- Copy `ssl_protocols TLSv1.2 TLSv1.3;` to `default.ssl.conf.erb`, and
- comment out `ssl_ciphers` there (to revert to Nginx default settings) or set it to the value in the SO post.
- Verified that `libssl1.1` is at least 1.1.1

I have not tried switching to [his docker image](https://hub.docker.com/r/admintuts/nginx/tags) yet, as this is Alpine-based, probably a larger adaptation required.

**Comment by SteveLTN** [comment]
I have tried several things from various places. Have no luck yet.

**Comment by SteveLTN** [comment]
I did find how to see it in Chrome though. It's in `Security` tab. Makes testing a bit faster.
![image](https://user-images.githubusercontent.com/508007/147679663-22271ac5-387c-456a-a2c3-f73ed41d8b6d.png)

**Comment by gerold-penz** [comment]
Hello,
can it be that it does not work only because Https portal uses an old Nginx version? `nginx:latest` is on version `1.23.1` at the moment. Https portal is currently using version `1.21.3`.
TLS 1.3 is becoming more and more important. [TLS-Checker](https://www.cdn77.com/tls-test) complains on my websites that TLS 1.3 is not enabled. I'm afraid I don't know how to help. 
I would like to see an update from Https portal to a newer Nginx version if I could wish for something.
Thanks a lot for your super work.
With kind regards, Gerold :-)

Translated with www.DeepL.com/Translator (free version)

**Comment by SteveLTN** [comment]
I will try tomorrow! I expect it to work out of the box with newer version
of Nginx, but should probably do some testing anyways.

**Comment by SteveLTN** [comment]
Fixed with 1.22 release.

**Comment by gerold-penz** [comment]
Thank you! :-)

**Comment by gerold-penz** [comment]
I just tried it on a test server with CUSTOM_NGINX_SERVER_CONFIG_BLOCK.

```
CUSTOM_NGINX_SERVER_CONFIG_BLOCK: |
  ssl_protocols TLSv1.2 TLSv1.3;
```

Works so far without any problems. :-)

**Comment by gerold-penz** [comment]
Addendum: CUSTOM_NGINX_SERVER_CONFIG_BLOCK is not necessary. It works also without this setting.
