### ISSUE TITLE
Multiple domains with redirect

### ISSUE THREAD

**Issue by bachp** [SteveLTN/https-portal#31]
It would be nice to be able to easily do the following setup:
- One certificate for multiple domains, e.g: `example.com` and `www.example.com`
- If the user visits `www.example.com` he should be redirected to `example.com`

Maybe it is already possible but I couldn't figure out how?

**Comment by SteveLTN** [comment]
Hi,

1. Is not possible currently. But since the certificates are free, you don't really need to use one cerfificate. Instead, creating one certificate for each of them will make the site a bit faster.
2. You need to provide a `www.example.com.conf.erb` and a `www.example.com.ssl.conf.erb`. See "Custom Nginx Configuration".

-- 
Weiyan Shao

On March 22, 2016 at 11:01:44 AM, Pascal Bach (notifications@github.com) wrote:

It would be nice to be able to easily do the following setup:

One certificate for multiple domains, e.g: example.com and www.example.com
If the user visits www.example.com he should be redirected to example.com
Maybe it is already possible but I couldn't figure out how?

**Comment by bachp** [comment]
Actually the example at: https://github.com/SteveLTN/https-portal/tree/master/examples/custom_config is excatly what I was looking for thank you.
