### ISSUE TITLE
Usage of web server without LetsEncrypt certificate

### ISSUE THREAD

**Issue by SasuGamerHD** [SteveLTN/https-portal#358]
Hey there. I am trying to install an instance of Outline which uses https-portal as the webserver as part of the docker composition. While all other services just run fine I get an error from https-portal which is unable to get a certificate for my domain. 

I wanted to ask: is there any .env variable or other option to use https-portal without it needing a certificate?
I have a certificate myself which I will use but can't for now as I need to move stuff from another server (which has the certificate) to this which I can only do if my instance of Outline is running.

I am not sure why a web server needs a certificate to just run? I understand that for security reasons I need a certificate and I will use one later in time. Also for another instance I want to install I need to turn this check off because I am in an airgapped environment with my own certificates.

Thanks in advance!

**Comment by SteveLTN** [comment]
I can't speak for the authors of Outline. I think maybe it's because the usage HTTPS is standard hygiene for a website nowadays. 

But the whole point of HTTPS-PORTAL is to wrap an HTTP website with HTTPS. If you are determined that you don't need HTTPS, then I think you can just skip HTTPS-PORTAL at all, and use the HTTP directly. Since HTTPS-PORTAL **requires** an working HTTP server, I imagine Outline already provide plain HTTP interface anyway.

**Comment by SteveLTN** [comment]
Oh, and HTTPS-PORTAL does provide a [local mode](https://github.com/SteveLTN/https-portal?tab=readme-ov-file#test-locally). It generates and uses a self-signed certificate. 

When using this mode, you need to accept security risk in your browser to continue. But if you use it in your internal network, it might work for you.
